### PR TITLE
Add Compilation & Testing On Windows

### PR DESCRIPTION
**Pull request by brianmichel**
**Requirements**

- [x] I have added test coverage for new or changed functionality
- [x] I have followed the repository's [pull request submission guidelines](../blob/main/CONTRIBUTING.md#submitting-pull-requests)
- [x] I have validated my changes against all supported platform versions

**Related issues**

I didn't see any related issues.

**Describe the solution you've provided**

This enables the ability to compile this library on Windows environments that are using Swift. I've chosen to use the recent 5.9 release as it should be a good candidate to base support on for this library. We can probably go older, but I thought we'd start at the most recent release.

**Describe alternatives you've considered**

N/A

**Additional context**

I saw that Circle CI is being used, however I don't know of a clean way to install Swift in a Circle CI instance (could probably figure this out), but to ensure that there was _some_ CI running and testing the Windows platform I've added a quick GitHub Action workflow that should also run and provide testing output.

### CODE REVIEW

**Comment by brianmichel** [comment]
It seems that the contract tests are broken on `main` as well as the other open PR (https://github.com/launchdarkly/swift-eventsource/pull/67) so I believe that breakage is unrelated to this PR. Clicking into the Circle CI build I see that tests do in fact still pass for all platforms (outside of the contract tests)

**Comment by keelerm84** [comment]
Good morning, and my apologies for not responding sooner!

I want you to know I will try to look at this PR soon and see about getting it merged in. I have some other work I have to attend to this iteration, but I have added a ticket to come back to this early next week.

Tracking internally as sc-218506.

**Comment by brianmichel** [comment]
Thanks @keelerm84!

**Comment by keelerm84** [comment]
@brianmichel just wanted to let you know I haven't forgotten about this. I had some last minute priority shifts which are going to take my attention for a bit.

**Review by keelerm84 — APPROVED** [review]

**Comment by keelerm84** [comment]
Sorry this took so long to review and get resolved. Thank you for your contribution!

**Pull request merged**
